### PR TITLE
Swerve Drive (maybe)

### LINKED ISSUE #39: Swerve Drive
**Summary**
Make a working swerve drive for the B team robot. I don't really know anything

**Work Scope**

- Create new drive command for swerve drive
- to be continued

**Verification**
The robot will drive correctly and not fail.

### PR DESCRIPTION
**Pull request by AlexEvergarden**
I made the SwerveModules, DriveAngle, Swerve Drive, and Robot State.
I added to DriveSubsystem and Constants.

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 1]
```diff
@@ -26,8 +46,36 @@ public DriveSubsystem(ChassisMode chassisMode, DriveMode driveMode) {
...
+            rotationPIDs[i].enableContinuousInput(-Math.PI, Math.PI);
+            driveModules[i].setDrivePD(DriveConstants.driveKps[i], DriveConstants.driveKds[i]);
+
+            modulePositions[i].distanceMeters = driveModules[i].getDrivePosition() * DriveConstants.wheelRadiusM;
+            modulePositions[i].angle = new Rotation2d(driveModules[i].getRotationPosition());
+        }
+
+        setGoalChassisSpeeds(new ChassisSpeeds(0, 0, 0));
+
+        RobotState.getInstance();//.initializePoseEstimator(getRotation(), modulePositions);
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java:49]: Put a TODO comment above this referencing odometry. I.e.
```
// TODO: add swerve drive odometry
```

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 2]
```diff
@@ -71,6 +119,110 @@ public void periodic(){
...
+            modulePositions[i].distanceMeters = driveModules[i].getDrivePosition() * DriveConstants.wheelRadiusM;
+            modulePositions[i].angle = new Rotation2d(driveModules[i].getRotationPosition());
+
+            SmartDashboard.putNumber("Drive/modules/"+i+"/angle", modulePositions[i].angle.getRadians());
+            SmartDashboard.putNumber("Drive/modules/"+i+"/drive stator current", driveModules[i].getDriveStatorCurrent());
+            SmartDashboard.putNumber("Drive/modules/"+i+"/rotation stator current", driveModules[i].getRotationStatorCurrent());
+        }
+        RobotState.getInstance().recordDriveObservations(/*getRotation(), modulePositions*/);
+
+        SmartDashboard.putNumber("Drive/velocity magnitude", getChassisSpeeds().vxMetersPerSecond);
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: Add comments explaining what all of this does

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 3]
```diff
@@ -71,6 +119,110 @@ public void periodic(){
...
+        SwerveDriveKinematics.desaturateWheelSpeeds(goalModuleStates, DriveConstants.maxDriveSpeed);
+        if (speeds.vxMetersPerSecond == 0 && speeds.vyMetersPerSecond == 0 && speeds.omegaRadiansPerSecond == 0) {
+            goalModuleStates = new SwerveModuleState[] {
+                new SwerveModuleState(0, modulePositions[0].angle), 
+                new SwerveModuleState(0, modulePositions[1].angle),
+                new SwerveModuleState(0, modulePositions[2].angle),
+                new SwerveModuleState(0, modulePositions[3].angle)
+            };
+        }
+        setGoalModuleStates(goalModuleStates);
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: Add comments explaining this code

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 4]
```diff
@@ -71,6 +119,110 @@ public void periodic(){
...
+    public double getRoll() {
+        return driveAngle.getRoll();
+    }
+
+    public void setBabyMode(boolean baby) {
+        babyMode = baby;
+    }
+
+    public void setFieldToVehicle(Pose2d fieldToVehicle) {
+        RobotState.getInstance().setFieldToVehicle(/*getRotation(), modulePositions, fieldToVehicle*/);
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java:129]: Add odometry TODO comment here

File: src/main/java/frc/robot/subsystems/drive/SwerveModules.java [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+    public void setRotationVoltage(double volts) {
+        rotationMotor.set(volts/12);
+    }
+
+    public void setDriveVoltage(double volts) {
+        driveMotor.set(volts/12);
+    }
+
+    public void setDriveVelocity(double velocityRadPerS, double ffVolts) {
+        //double velocityTicksPer100ms = velocityRadPerS * 2048.0 / 10.0 / 2.0 / Math.PI * DriveConstants.driveWheelGearReduction;
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/SwerveModules.java]: Is this comment relevant? If not, let's remove it

File: src/main/java/frc/robot/subsystems/drive/SwerveModules.java [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+        return MathUtil.angleModulus(Units.degreesToRadians(rotationEncoder.getPosition())) - initialOffsetRadians;
+    }
+
+    public double getRotationVelocity() {
+        return Units.degreesToRadians(rotationEncoder.getVelocity());
+    }
+
+    public double getDriveVelocityMPerS() {
+        return driveMotor.getEncoder().getVelocity() / 2048.0 * 10.0 * 2 * Math.PI * DriveConstants.wheelRadiusM / DriveConstants.driveWheelGearReduction;
+    }       //veclocity gives Rotations per minute, need to go to radians per second
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/SwerveModules.java]: "veclocity"

Also this comment should be moved into the function instead of being under it

File: src/main/java/frc/robot/subsystems/drive/SwerveModules.java [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+    }
+
+    public void setBrake(boolean braked) {
+        driveMotor.setIdleMode(braked ? IdleMode.kBrake : IdleMode.kCoast);
+        rotationMotor.setIdleMode(braked ? IdleMode.kBrake : IdleMode.kCoast);
+    }
+
+
+
+
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/SwerveModules.java]: nitpick: remove all these extra spaces

File: src/main/java/frc/robot/subsystems/drive/DriveAngle.java
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveAngle.java:1]: What is the purpose of this class? It looks like it's mostly being used to interface with the IMU.

This code seems useful, but maybe the class should be renamed. Also it is extending SubsystemBase, which probably isn't right. I think it would be best if this became a helper class used within DriveSubsystem

File: src/main/java/frc/robot/Constants.java [hunk 8]
```diff
@@ -33,12 +38,57 @@ public final class ArmConstants {
...
+        public static final double driveJoystickDeadbandPercent = 0;
+
+        public static final double maxDriveSpeed = 0;
+        public static final double maxTurnRate = 0;
+
+        public static final double[] driveKps = {0.7, 0.4, 0.7, 0.7};
+        public static final double[] driveKds = {3.5, 2.5, 3.7, 3.5};
+
+        public static final double[] rotationKps = {7, 7, 7, 7};
+        public static final double[] rotationKds = {0, 0, 0, 0};
```
Comment (jkleiber) [inline src/main/java/frc/robot/Constants.java]: It would be good to make these values available for tuning on SmartDashboard/Shuffleboard.

File: src/main/java/frc/robot/Constants.java [hunk 9]
```diff
@@ -33,12 +38,57 @@ public final class ArmConstants {
     }
 
     public static final class DriveConstants {
+
+        public static final double trackWidth = Units.inchesToMeters(17.75);
+        public static final double wheelBase = Units.inchesToMeters(23.75);
```
Comment (jkleiber) [inline src/main/java/frc/robot/Constants.java]: have these numbers been actually measured? If not, let's make a comment that we need to measure these and that they are placeholder numbers

File: src/main/java/frc/robot/Constants.java [hunk 10]
```diff
@@ -33,12 +38,57 @@ public final class ArmConstants {
...
+
+        public static final int frontLeftRotationEncoderID = 0;
+        public static final int frontRightRotationEncoderID = 0;
+        public static final int backLeftRotationEncoderID = 0;
+        public static final int backRightRotationEncoderID = 0;
+
+        public static final double frontLeftAngleOffset = 0.0;
+        public static final double frontRightAngleOffset = 0.0;
+        public static final double backLeftAngleOffset = 0.0;
+        public static final double backRightAngleOffset = 0.0;
```
Comment (jkleiber) [inline src/main/java/frc/robot/Constants.java]: Add a comment that these are placeholders (even though it is obvious)

File: src/main/java/frc/robot/Constants.java [hunk 11]
```diff
@@ -33,12 +38,57 @@ public final class ArmConstants {
...
+
+        public static final SwerveDriveKinematics kinematics = 
+            new SwerveDriveKinematics(
+                new Translation2d(trackWidth / 2.0, wheelBase / 2.0), //front left
+                new Translation2d(trackWidth / 2.0, -wheelBase / 2.0), //front right
+                new Translation2d(-trackWidth / 2.0, wheelBase / 2.0), //rear left
+                new Translation2d(-trackWidth / 2.0, -wheelBase / 2.0) //rear right
+        );
+
+        public static final SimpleMotorFeedforward driveFF = new SimpleMotorFeedforward(0.24, 2.185);
```
Comment (jkleiber) [inline src/main/java/frc/robot/Constants.java]: Are these placeholders or known values?

File: src/main/java/frc/robot/Constants.java [hunk 12]
```diff
@@ -33,12 +38,57 @@ public final class ArmConstants {
...
+
+        public static final int pigeonIMU = 0;
+        
+        public static final double driveJoystickDeadbandPercent = 0;
+
+        public static final double maxDriveSpeed = 0;
+        public static final double maxTurnRate = 0;
```
Comment (jkleiber) [inline src/main/java/frc/robot/Constants.java]: Comment placeholder status for each of these blocks of code

File: src/main/java/frc/robot/commands/drive/SwerveDrive.java [hunk 13]
```diff
@@ -0,0 +1,72 @@
...
+import frc.robot.subsystems.drive.DriveSubsystem;
+
+public class SwerveDrive extends CommandBase{
+    private final DriveSubsystem drive;
+    private final DoubleSupplier xPercent;
+    private final DoubleSupplier yPercent;
+    private final DoubleSupplier omegaPercent;
+    private final boolean fieldRelative;
+
+    /** Creates a new DriveWithJoysticks. */
```
Comment (jkleiber) [inline src/main/java/frc/robot/commands/drive/SwerveDrive.java]: This comment is stale

File: src/main/java/frc/robot/commands/drive/SwerveDrive.java [hunk 14]
```diff
@@ -0,0 +1,72 @@
...
+
+
+import java.util.function.DoubleSupplier;
+
+import edu.wpi.first.math.kinematics.ChassisSpeeds;
+import frc.robot.Constants.DriveConstants;
+import edu.wpi.first.wpilibj2.command.CommandBase;
+import frc.robot.subsystems.drive.DriveSubsystem;
+
+public class SwerveDrive extends CommandBase{
```
Comment (jkleiber) [inline src/main/java/frc/robot/commands/drive/SwerveDrive.java]: This command name could be easily confused with a subsystem. Maybe name this "SwerveDriveCommand" or something that clearly indicates that it is not the Swerve Drive itself.

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 15]
```diff
@@ -71,6 +119,110 @@ public void periodic(){
...
+
+        for (int i = 0; i < 4; i++) {
+            modulePositions[i].distanceMeters = driveModules[i].getDrivePosition() * DriveConstants.wheelRadiusM;
+            modulePositions[i].angle = new Rotation2d(driveModules[i].getRotationPosition());
+
+            SmartDashboard.putNumber("Drive/modules/"+i+"/angle", modulePositions[i].angle.getRadians());
+            SmartDashboard.putNumber("Drive/modules/"+i+"/drive stator current", driveModules[i].getDriveStatorCurrent());
+            SmartDashboard.putNumber("Drive/modules/"+i+"/rotation stator current", driveModules[i].getRotationStatorCurrent());
+        }
+        RobotState.getInstance().recordDriveObservations(/*getRotation(), modulePositions*/);
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java:76]: Add a TODO comment about odometry

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 16]
```diff
@@ -71,6 +119,110 @@ public void periodic(){
         else {
             driveHardware.arcadeDrive(arcadeForward, arcadeRotation);
         }
-    } 
 
-}
+        for (int i = 0; i < 4; i++) {
+
+            //SmartDashboard.putBoolean("Drive/modules/"+i+"/status", driveModules[i].getDeadBoolean());
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: If this is a dead comment, let's delete it

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 17]
```diff
@@ -14,6 +31,9 @@ public class DriveSubsystem extends SubsystemBase{
     private double rightTank = 0;
     private double arcadeForward = 0;
     private double arcadeRotation = 0;
+    
+    private boolean babyMode = false;
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java:21]: Please open an Issue to allow babyMode to be toggled using a button on one of the joysticks

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 18]
```diff
@@ -26,8 +46,36 @@ public DriveSubsystem(ChassisMode chassisMode, DriveMode driveMode) {
...
+        driveModules[3] = new SwerveModules(DriveConstants.backRightID, DriveConstants.backRightRotationMotorID,
+        DriveConstants.backRightRotationEncoderID, DriveConstants.backRightAngleOffset, true, false);
+
+        for (int i = 0; i < 4; i++) {
+            driveModules[i].zeroEncoders();
+            modulePositions[i] = new SwerveModulePosition();
+            goalModuleStates[i] = new SwerveModuleState();
+
+            rotationPIDs[i] = new PIDController(DriveConstants.rotationKps[i], 0, DriveConstants.rotationKds[i]);
+            rotationPIDs[i].enableContinuousInput(-Math.PI, Math.PI);
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: Let's make the rotationPIDs a part of the SwerveModules class, since it seems like that class should be able to manage its own rotation control

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 19]
```diff
@@ -71,6 +119,110 @@ public void periodic(){
...
+            SwerveModuleState optimizedState = SwerveModuleState.optimize(goalModuleStates[i], moduleRotation);
+            double rotationSetpointRadians = optimizedState.angle.getRadians();
+            double speedSetpointMPerS = optimizedState.speedMetersPerSecond;
+
+            double speedRadPerS = speedSetpointMPerS / DriveConstants.wheelRadiusM;
+            double ffVolts = DriveConstants.driveFF.calculate(speedRadPerS);
+            driveModules[i].setDriveVelocity(speedRadPerS, ffVolts);
+
+            double rotationVoltage = rotationPIDs[i].calculate(moduleRotation.getRadians(), rotationSetpointRadians);
+            driveModules[i].setRotationVoltage(rotationVoltage);
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: It seems like we should move this into the SwerveModules class. Then we can have a function called controlModule that takes a goal state and does the control for drive power and rotation. DriveSubsystem should orchestrate the modules, and the modules should control themselves.

**Review by jkleiber — CHANGES_REQUESTED** [review]
First pass review

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 20]
```diff
@@ -71,6 +119,107 @@ public void periodic(){
...
-    } 
 
-}
+        for (int i = 0; i < 4; i++) {
+            //Get encoder value
+            Rotation2d moduleRotation = new Rotation2d(driveModules[i].getRotationPosition());
+
+            //Optimize each module state
+            SwerveModuleState optimizedState = SwerveModuleState.optimize(goalModuleStates[i], moduleRotation);
+            driveModules[i].moduleControl(optimizedState, moduleRotation);
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: Does moduleControl need moduleRotation as an input? Doesn't it already have that?

File: src/main/java/frc/robot/subsystems/drive/SwerveModules.java [hunk 21]
```diff
@@ -0,0 +1,145 @@
...
+    private final PIDController drivePID = new PIDController(0, 0, 0);
+    private PIDController rotationPID = new PIDController(0,0,0);
+
+    //private final CANCoder driveEncoder;  it is built in
+    private final CANCoder rotationEncoder;
+
+    private final double initialOffsetRadians;
+
+    public SwerveModules(int driveModeID, int turningMotorID, int cancoderID, double measuredOffsetsRadians, boolean driveModeReversed, boolean turningMotorReversed
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/SwerveModules.java]: probably should rename "driveModeID" to driveMotorID

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 22]
```diff
@@ -1,11 +1,28 @@
...
+
+    private final SwerveModules[] driveModules = new SwerveModules[4];
+    private final DriveAngle driveAngle = new DriveAngle();
+    private SwerveModulePosition modulePositions[] = new SwerveModulePosition[4];
+    private SwerveModuleState[] goalModuleStates = new SwerveModuleState[4];
+    private PIDController[] rotationPIDs = new PIDController[4];
+
     private DriveMode mode;
 
     private DriveHardware driveHardware;
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: Let's get rid of drive hardware related things from DriveSubsystem for now

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 23]
```diff
@@ -1,11 +1,28 @@
...
+import frc.robot.RobotState;
 
 public class DriveSubsystem extends SubsystemBase{
 
+
+    private final SwerveModules[] driveModules = new SwerveModules[4];
+    private final DriveAngle driveAngle = new DriveAngle();
+    private SwerveModulePosition modulePositions[] = new SwerveModulePosition[4];
+    private SwerveModuleState[] goalModuleStates = new SwerveModuleState[4];
+    private PIDController[] rotationPIDs = new PIDController[4];
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: these should be removed now that SwerveModules handles this

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java [hunk 24]
```diff
@@ -26,8 +46,36 @@ public DriveSubsystem(ChassisMode chassisMode, DriveMode driveMode) {
...
+        //TODO: add swerve drive odometry
+        setGoalChassisSpeeds(new ChassisSpeeds(0, 0, 0));
+        RobotState.getInstance();//.initializePoseEstimator(getRotation(), modulePositions);
     }
 
+    
+
     public DriveSubsystem(ChassisMode chassisMode) {
         this(chassisMode, DriveMode.TANKDRIVE);
     }
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: We should remove references to tank and arcade drive throughout the file

**Review by jkleiber — CHANGES_REQUESTED** [review]
Second pass

File: src/main/java/frc/robot/subsystems/drive/SwerveModules.java [hunk 25]
```diff
@@ -0,0 +1,145 @@
...
+        rotationMotor.set(volts/12);
+    }
+
+    public void setDriveVoltage(double volts) {
+        driveMotor.set(volts/12);
+    }
+
+    public void setDriveVelocity(double velocityRadPerS) {
+        /*double velocityTicksPer100ms = velocityRadPerS * 2048.0 / 10.0 / 2.0 / Math.PI * DriveConstants.driveWheelGearReduction;
+        driveMotor.set(ffVolts / 12.0);*/
```
Comment (jkleiber) [inline src/main/java/frc/robot/subsystems/drive/SwerveModules.java]: what is this commented code?

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java (hunk 20 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: fixed

File: src/main/java/frc/robot/subsystems/drive/SwerveModules.java (hunk 21 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/SwerveModules.java]: changed

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java (hunk 2 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: fixed

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java (hunk 3 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: done

File: src/main/java/frc/robot/subsystems/drive/SwerveModules.java (hunk 5 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/SwerveModules.java]: removed it

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java (hunk 18 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: done

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java (hunk 19 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: done

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java (hunk 22 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: done

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java (hunk 24 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: done

File: src/main/java/frc/robot/subsystems/drive/SwerveModules.java (hunk 25 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/SwerveModules.java]: I deleted it

File: src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java (hunk 23 above)
Comment (AlexEvergarden) [reply src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java]: done

**Review by jkleiber — APPROVED** [review]
LGTM
